# Example secrets file - Copy this to .streamlit/secrets.toml and add your values

alchemy_api_key = "your_alchemy_api_key_here"

# Optional: Nillion Testnet Network Configuration: https://docs.nillion.com/network-configuration
# If the env variables below are not set network will default to use Network.from_config("devnet")

# Connect to Nillion Testnet: https://docs.nillion.com/network 
# nilchain_key = "your_nilchain_testnet_funded_private_key_here"
# nillion_chain_id = "nillion-chain-testnet-1"
# nillion_nilvm_bootnode = "https://node-1.nilvm-testnet-1.nillion-network.testnet.nillion.network:14311"
# nillion_nilchain_grpc = "https://testnet-nillion-grpc.lavenderfive.com"
